"""add owner_token to buckets

Revision ID: 005be1b71867
Revises: c8038f5368cf
Create Date: 2026-09-02 14:08:26.982164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '005be1b71867'
down_revision: Union[str, Sequence[str], None] = 'c8038f5368cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buckets', sa.Column('owner_token', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'buckets', ['owner_token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'buckets', type_='unique')
    op.drop_column('buckets', 'owner_token')
    # ### end Alembic commands ###
